### ISSUE TITLE
[TODO] In Game Chat Component

### ISSUE THREAD

**Issue by JMBeresford** [JMBeresford/chessclub#22]
# In Game Chat Component

## The in game chat component on the active game page needs to be built out. 

![image](https://user-images.githubusercontent.com/1373954/118344059-2b2ddf80-b4e1-11eb-8c07-b02871d8b91b.png)

### Description:
Eventually this will incorporate the use of web-sockets, but for now we will use helper functions to simulate chat functionality. The component will have an array of message objects called `messages` in its data section that has the form defined in the **Data** section below.

> **IMPORTANT**: Note that a `user_id` of 0 in any of these objects indicates a *system message*, and those messages are styled differently than the user messages as can be seen in the reference image.

To tackle this you will likely want the section that the actual messages are in with the following styles:

```scss
.chatContainer: {
  // these two lines set up the container to have its children stack vertically
  // and allow the use of flex utilities
  display: flex;
  flex-direction: column;

  // this line ensures that content stays at the bottom of the container
  // and stacks upwards as messages are added thanks to the flex-direction
  justify-content: flex-end;

  overflow-y: scroll;
}
```

### Elements that are given:
Pretty much nothing other than the `<div>` you need to work in. The images of the knights are available in the `static/img/pieces/` directory, as always.

## TODO:
- Inputs (props)
  - You will have access to the `game` object, which follows the model defined in `models.py`.
  - You will also have a players object defined as such: `players = { "white": <player_white>, "black": <player_black> }`
    - `player_white` and `player_black` will be `user` objects containing the IDs and usernames of the respective players.
- Data
  - `messages` should be as described above, which will be copied here:
    - `messages = [ { "user_id": 2, "msg": "Haha nice move" }, { "user_id": 3, "msg": "ur gonna lose" }, { "user_id": 0, "msg": "Check" }, . . . ]`
- Methods
  - You must define a `userMessage()` function that pushes the new message object to `this.messages`.
    - Something like `userMessage(id, msg)`
  - Do likewise for system messages (remember a system message is denoted by an ID of 0!)
    - Something like `sysMessage(msg)`
      - I would suggest binding these two functions to the `@click` event on the knight images in the header of this component. Temporarily, of course, for testing during development.
  - A `sendMessage()` function which will, eventually, emit an event through the websocket with the currently typed message. For now this can just be a `console.log` when a user either presses enter in the chatbox or clicks the send button.
 
### You should create a git commit with the at most the following changes:
- `templates/game.html` with any changes to the template (unlikely, but allowed)
- `static/js/components/game/ingamechat.js` which includes the Vue component and/or additional javascript as needed
- `static/css/game/_ingamechat.scss` for the styles for this component (regular css works in `.scss` files! This file *must* be used)
  - Any additional `.scss` files can be used so long as they are in the `static/css/game/` directory
  - **Make sure** you include them in the existing `_game.scss` file with `@use(<new_filename>)` (no, the `.scss` is not needed)
  
  # If you have any questions, or need assistance just reach out in the Slack channel 😄 
  ## Thanks for the great teamwork 👍🏻
